# Generated by Django 3.2.4 on 2021-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommDisaster',
        ),
        migrations.RemoveField(
            model_name='brickwoodstructure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='civilstructure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deathstatistics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='frameworkstructure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='injuredstatistics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='masonrystructure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='missingstatistics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='otherstructure',
            name='id',
        ),
        migrations.AlterField(
            model_name='brickwoodstructure',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='civilstructure',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deathstatistics',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frameworkstructure',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='injuredstatistics',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masonrystructure',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='missingstatistics',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherstructure',
            name='ID',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
    ]
