# Generated by Django 3.2.4 on 2021-06-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mshd', '0002_auto_20210613_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickwoodstructure',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='civilstructure',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='deathstatistics',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='frameworkstructure',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='injuredstatistics',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='masonrystructure',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='missingstatistics',
            old_name='ID',
            new_name='fuck',
        ),
        migrations.RenameField(
            model_name='otherstructure',
            old_name='ID',
            new_name='fuck',
        ),
    ]
