# Generated by Django 3.2.4 on 2021-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mshd', '0003_auto_20210613_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickwoodstructure',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='civilstructure',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='deathstatistics',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='frameworkstructure',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='injuredstatistics',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='masonrystructure',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='missingstatistics',
            old_name='fuck',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='otherstructure',
            old_name='fuck',
            new_name='ID',
        ),
    ]
